[package]
name = "open-meta-id"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.0"
anyhow = "1.0.53"
argon2 = "0.3.3"
konst = "0.2.13"
k256 = { version = "0.10.2", features = ["ecdh", "ecdsa"]}
rand_core = "0.6.3"
thiserror = "1.0.30"
